CREATE DATABASE STUDENTSREG;
USE STUDENTSREG;
CREATE TABLE TUTOR (
  Tut_Id VARCHAR(10) NOT NULL,
  TName VARCHAR(45) NOT NULL,
  DoB DATE NOT NULL,
  HOURS DOUBLE, 
  PRIMARY KEY (Tut_Id)
  );
  
CREATE TABLE STUDENT
(
SID VARCHAR(10) NOT NULL, 
PRIMARY KEY (SID),
SNAME VARCHAR(30),
EMAIL VARCHAR(30),
Tutor_Id VARCHAR (10) NULL, 
FOREIGN KEY (Tutor_Id)
  REFERENCES TUTOR (Tut_Id)
  ON DELETE SET NULL
  ON UPDATE CASCADE
);

CREATE TABLE MODULES
(
MID VARCHAR(15) NOT NULL, 
PRIMARY KEY (MID),
MNAME VARCHAR(40),
LEVEL VARCHAR(2),
TUTOR_Tut_Id VARCHAR(10), 
FOREIGN KEY(TUTOR_Tut_Id) REFERENCES TUTOR (Tut_Id) 
  ON UPDATE CASCADE 
    ON DELETE SET NULL
);

CREATE TABLE STUDENT_ENROLEMENT
(
SID VARCHAR(10) NOT NULL, 
FOREIGN KEY (SID) REFERENCES STUDENT(SID),
MID VARCHAR(15) NOT NULL, 
FOREIGN KEY (MID) REFERENCES MODULES(MID),
ACAD_YEAR VARCHAR(10),
PRIMARY KEY (SID, MID, ACAD_YEAR)
);
